apiVersion: skaffold/v4beta5
kind: Config
build:
  artifacts:
    - image: neat1144/auth
    # - image: us.gcr.io/gold-optics-387009/auth
      context: auth
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
    
    - image: neat1144/client
    # - image: us.gcr.io/gold-optics-387009/client
      context: client
      sync:
        manual:
          - src: '**/*.js'
            dest: .
      docker:
        dockerfile: Dockerfile
    
  local:
    push: false
  # googleCloudBuild:
    # projectId: gold-optics-387009
manifests:
  rawYaml:
    - ./infra/k8s/*
deploy:
  kubectl: {}